apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-inspector
  labels:
    app: rabbit-mq-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq-inspector
  template:
    metadata:
      labels:
        app: rabbit-mq-inspector
    spec:
      serviceAccountName: rabbit-mq-puller-sa
      containers:
        - name: rabbit-mq-inspector
          image: qoosdd89382/rabbit-mq-inspector
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: rabbit-mq-inspector-config
