apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rabbit-mq-inspector-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: rabbit-mq-inspector-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-lister
  apiGroup: rbac.authorization.k8s.io
